spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haribo?serverTimezone=Asia/Seoul
    username: haribo
    password: 1